# Generated by Django 3.0.8 on 2020-07-30 09:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200729_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, null=True)),
                ('age', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cin', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200)),
                ('assurance', models.CharField(choices=[('CNSS', 'CNSS'), ('CNOPS', 'CNOPS'), ('AXA', 'AXA'), ('SAHAM', 'SAHAM'), ('Autre', 'Autre')], max_length=200)),
                ('date_created', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rendezvous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Consultation', 'Consultation'), ('Controle', 'Controle'), ('Geste Chirurgical', 'Geste Chirurgical')], max_length=200)),
                ('motif', models.CharField(max_length=200)),
                ('date_rendezvous', models.DateField(auto_now_add=True, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Patient')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
