# Generated by Django 3.0.8 on 2020-07-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200730_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='montant',
            field=models.FloatField(null=True),
        ),
    ]
