# Generated by Django 3.0.8 on 2020-08-01 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rendezvous_montant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
                ('rv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Imagerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
                ('rv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
                ('rv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Patient')),
            ],
        ),
    ]
