# Generated by Django 3.0.8 on 2020-08-03 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200801_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerie',
            name='document',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='facture',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='facture',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='imagerie',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='assurance',
            field=models.CharField(blank=True, choices=[('CNSS', 'CNSS'), ('CNOPS', 'CNOPS'), ('AXA', 'AXA'), ('SAHAM', 'SAHAM'), ('Autre', 'Autre')], max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='montant',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='motif',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
