# Generated by Django 3.0.8 on 2020-08-04 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200803_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='description',
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='revoir_dans',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='facture',
            name='rv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Rendezvous'),
        ),
        migrations.AlterField(
            model_name='imagerie',
            name='document',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='rv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Rendezvous'),
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200, null=True)),
                ('montant', models.FloatField(null=True)),
                ('facture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Facture')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posologie', models.CharField(blank=True, max_length=100, null=True)),
                ('medicament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Medicament')),
                ('ordonnance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Ordonnance')),
            ],
        ),
    ]
